export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const SAVE_IMAGEID = 'SAVE_IMAGEID';
export const SAVE_DETAILS = 'SAVE_DETAILS';
export const CLEAN_DETAILS = 'CLEAN_DETAILS';
export const IMAGES_VISIBLE = 'IMAGES_VISIBLE';